export interface User {
    id: number
    steam_id: string
    steam_id_v3: string
    steam_name: string
    avatar: string
    profile_url: string
    registration_timestamp: string
    registration_ip: string
    last_login: string
    balance: number
    total_profit: number
    total_bet: number
    betback_total: number
    bet_threshold: number
    total_trades: number
    total_deposit: number
    total_withdraw: number
    withdraw_limit: number
    csgo_playtime: number
    last_csgo_playtime_cache: string
    trade_url: string
    trade_offer_token: string
    ref_id: number
    total_referral_bet: number
    total_referral_commission: number
    ref_permission: number
    ref_earnings: number
    total_ref_earnings: number
    total_ref_count: number
    total_credit: number
    referral_code: string
    referral_amount: number
    muted_until: number
    mute_reason: string
    admin: number
    super_mod: number
    mod: number
    utm_campaign: string
    country: string
    is_vac_banned: number
    steam_level: number
    last_steam_level_cache: string
    whitelisted: number
    total_tips_received: number
    total_tips_sent: number
    withdrawal_fee_owed: string
    flags: number
    ban: null
    balances: []
    level: number
    xp: number
    socket_token: string
    user_hash: string
    hashed_server_seed: string
    intercom_hash: string
    roles: []
    eligible_for_free_case: boolean
    extra_security_type: string
    total_bet_skincrash: number
    total_bet_matchbetting: number
    total_bet_roulette: number
    total_bet_coinflip: number
    total_bet_supershootout: number
    p2p_telegram_notifications_allowed: true
    p2p_telegram_notifications_enabled: true
    verified: boolean
    hide_verified_icon: boolean
    unread_notifications: []
    last_session: {}
    email: string
    email_verified: boolean
    eth_deposit_address: string
    btc_deposit_address: string
    ltc_deposit_address: string
    bch_deposit_address: string
    steam_inventory_url: string
    steam_api_key: string
    has_crypto_deposit: true
    chat_tag: {}
    linked_accounts: []
    api_token: string
}
